name: Release

on:
  workflow_run:
    workflows: ["Build Ubuntu", "Build Windows"]
    types: [completed]

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')  # ensure it only runs for tags
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-artifact
          path: release/linux

      - name: download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-artifact
          path: release/windows

      - name: create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            release/linux/**
            release/windows/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
